using System;
using System.Linq;
using System.Text;

using EdaSimulator.Engines.Models;
using EdaSimulator.Engines.Models.Components;

namespace EdaSimulator.Engines.Simulation
{
    /// <summary>
    /// Responsible for converting a Schematic graph into a valid SPICE netlist (.cir) format.
    /// </summary>
    public class SpiceNetlistExporter
    {
        /// <summary>
        /// Generates the full SPICE netlist from the given schematic.
        /// </summary>
        /// <param name="schematic">The master circuit graph to export.</param>
        /// <param name="simulationDirective">Optional simulation command (e.g., ".tran 1m 10m", ".op"). Defaults to ".op".</param>
        /// <returns>A string representing the complete .cir file content.</returns>
        public string GenerateNetlist(Schematic schematic, string simulationDirective = ".op")
        {
            ArgumentNullException.ThrowIfNull(schematic);

            var sb = new StringBuilder();

            // 1. Header & Title (First line in SPICE is ALWAYS the title/comment)
            sb.AppendLine($"* {schematic.Title}");
            sb.AppendLine("* Netlist automatically generated by EDA Simulator Platform");
            sb.AppendLine(".options savecurrents");
            sb.AppendLine();

            // 1.5 Includes — bundled model library first, then user includes
            sb.AppendLine("* --- Model Libraries ---");

            // Auto-inject bundled SPICE model library if available
            var modelLib = ModelLibraryService.Instance;
            if (modelLib.IsLoaded && !string.IsNullOrEmpty(modelLib.LibraryFilePath))
            {
                sb.AppendLine($".include \"{modelLib.LibraryFilePath}\"");
            }

            if (schematic.SpiceIncludes.Count > 0)
            {
                sb.AppendLine("* --- Includes ---");
                foreach (var include in schematic.SpiceIncludes)
                {
                    sb.AppendLine($".include \"{include}\"");
                }
                sb.AppendLine();
            }

            // 2. Validate schematic for fundamental errors before export
            var issues = schematic.Validate();
            if (issues.Any())
            {
                sb.AppendLine("* LOG: Validation issues detected:");
                foreach (var issue in issues)
                {
                    sb.AppendLine($"*  - {issue}");
                }
                sb.AppendLine();
            }

            // 3. Components
            // Order component exports alphabetically by designator for clean readability
            var sortedComponents = schematic.Components.Values
                .OrderBy(c => c.Designator, StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (sortedComponents.Count > 0)
            {
                sb.AppendLine("* --- Components ---");
                foreach (var component in sortedComponents)
                {
                    // Generate string for this specific component polymorphically
                    string spiceLine = component.GenerateSpiceNetlistLine(schematic);
                    sb.AppendLine(spiceLine);
                }
                sb.AppendLine();
            }
            else
            {
                sb.AppendLine("* --- No Components Found ---");
                sb.AppendLine();
            }

            // 4. Analysis / Directives
            sb.AppendLine("* --- Simulation Control ---");
            if (!string.IsNullOrWhiteSpace(simulationDirective))
            {
                // Explicit directive from caller takes priority (e.g., .tran, .ac dec, .dc)
                sb.AppendLine(simulationDirective);
            }
            else
            {
                // Fall back to schematic-embedded SimConfig directive
                string configDirective = schematic.SimConfig.GetSpiceDirective();
                if (!string.IsNullOrEmpty(configDirective))
                {
                    sb.AppendLine(configDirective);
                }
            }

            // 4.5 MCU Subcircuit Definitions
            var mcus = schematic.Components.Values.OfType<McuComponent>().ToList();
            if (mcus.Count > 0)
            {
                sb.AppendLine("* --- MCU Subcircuit Definitions ---");
                var uniqueMcuTypes = mcus.GroupBy(m => m.GetSubcircuitName()).Select(g => g.First());
                foreach (var mcu in uniqueMcuTypes)
                {
                    string subcktName = mcu.GetSubcircuitName();
                    var pinNames = string.Join(" ", mcu.Pins.Select(p => mcu.GetSanitizedPinName(p)));
                    sb.AppendLine($".SUBCKT {subcktName} {pinNames}");
                    foreach (var pin in mcu.Pins)
                    {
                        string safePin = mcu.GetSanitizedPinName(pin);
                        sb.AppendLine($"R_{safePin} {safePin} 0 1G");
                    }
                    sb.AppendLine($".ENDS {subcktName}");
                    sb.AppendLine();
                }
            }

            // 4.6 Mathematical Block Diagram Subcircuit Library
            bool hasBlockComponents = schematic.Components.Values.Any(c => c is BlockComponent);
            if (hasBlockComponents)
            {
                sb.AppendLine("* --- Mathematical Block Subcircuit Library ---");
                
                sb.AppendLine(".SUBCKT BlockGain IN OUT params: gain=1");
                sb.AppendLine("Egain OUT 0 IN 0 {gain}");
                sb.AppendLine(".ENDS BlockGain");
                sb.AppendLine();

                sb.AppendLine(".SUBCKT BlockIntegrator IN OUT params: ic=0");
                sb.AppendLine("Gint 0 OUT value={ V(IN) }");
                sb.AppendLine("Cint OUT 0 1.0 ic={ic}");
                sb.AppendLine("Rint OUT 0 1G");
                sb.AppendLine(".ENDS BlockIntegrator");
                sb.AppendLine();

                sb.AppendLine(".SUBCKT BlockSum2 IN1 IN2 OUT params: sign1=1 sign2=-1");
                sb.AppendLine("Esum OUT 0 value={ sign1 * V(IN1) + sign2 * V(IN2) }");
                sb.AppendLine(".ENDS BlockSum2");
                sb.AppendLine();

                sb.AppendLine(".SUBCKT BlockSourceConst OUT params: val=1");
                sb.AppendLine("Vsrc OUT 0 DC {val}");
                sb.AppendLine(".ENDS BlockSourceConst");
                sb.AppendLine();

                sb.AppendLine(".SUBCKT BlockSourceSine OUT params: offset=0 amp=1 freq=1k phase=0");
                sb.AppendLine("Vsrc OUT 0 SIN({offset} {amp} {freq} 0 0 {phase})");
                sb.AppendLine(".ENDS BlockSourceSine");
                sb.AppendLine();

                sb.AppendLine(".SUBCKT BlockSourceStep OUT params: offset=0 stepval=1 steptime=1");
                sb.AppendLine("Vsrc OUT 0 PWL(0 {offset} {steptime-1u} {offset} {steptime} {stepval})");
                sb.AppendLine(".ENDS BlockSourceStep");
                sb.AppendLine();
            }

            sb.AppendLine(".end");
            return sb.ToString();
        }
    }
}
