using System;
using System.Linq;
using System.Text;

using EdaSimulator.Engines.Models;

namespace EdaSimulator.Engines.Simulation
{
    /// <summary>
    /// Responsible for converting a Schematic graph into a valid SPICE netlist (.cir) format.
    /// </summary>
    public class SpiceNetlistExporter
    {
        /// <summary>
        /// Generates the full SPICE netlist from the given schematic.
        /// </summary>
        /// <param name="schematic">The master circuit graph to export.</param>
        /// <param name="simulationDirective">Optional simulation command (e.g., ".tran 1m 10m", ".op"). Defaults to ".op".</param>
        /// <returns>A string representing the complete .cir file content.</returns>
        public string GenerateNetlist(Schematic schematic, string simulationDirective = ".op")
        {
            ArgumentNullException.ThrowIfNull(schematic);

            var sb = new StringBuilder();

            // 1. Header & Title (First line in SPICE is ALWAYS the title/comment)
            sb.AppendLine($"* {schematic.Title}");
            sb.AppendLine("* Netlist automatically generated by EDA Simulator Platform");
            sb.AppendLine();

            // 2. Validate schematic for fundamental errors before export
            var issues = schematic.Validate();
            if (issues.Any())
            {
                sb.AppendLine("* LOG: Validation issues detected:");
                foreach (var issue in issues)
                {
                    sb.AppendLine($"*  - {issue}");
                }
                sb.AppendLine();
            }

            // 3. Components
            // Order component exports alphabetically by designator for clean readability
            var sortedComponents = schematic.Components.Values
                .OrderBy(c => c.Designator, StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (sortedComponents.Count > 0)
            {
                sb.AppendLine("* --- Components ---");
                foreach (var component in sortedComponents)
                {
                    // Generate string for this specific component polymorphically
                    string spiceLine = component.GenerateSpiceNetlistLine(schematic);
                    sb.AppendLine(spiceLine);
                }
                sb.AppendLine();
            }
            else
            {
                sb.AppendLine("* --- No Components Found ---");
                sb.AppendLine();
            }

            // 4. Analysis / Directives
            sb.AppendLine("* --- Simulation Control ---");
            if (!string.IsNullOrWhiteSpace(simulationDirective))
            {
                sb.AppendLine(simulationDirective);
            }
            
            // 5. Control Block end
            sb.AppendLine();
            sb.AppendLine(".end");

            return sb.ToString();
        }
    }
}
